%YAML 1.2
---
name: One dark
parent-scheme: Darcula
colors:
  ADDED_LINES_COLOR: green
  CARET_COLOR: 528bff
  CARET_ROW_COLOR: 2c313c
  CONSOLE_BACKGROUND_KEY: 282c34
  DELETED_LINES_COLOR: coral
  ERROR_HINT: '781732'
  FOLDED_TEXT_BORDER_COLOR: ''
  GUTTER_BACKGROUND: 282c34
  HTML_TAG_TREE_LEVEL0: error
  HTML_TAG_TREE_LEVEL1: chalky
  HTML_TAG_TREE_LEVEL2: green
  HTML_TAG_TREE_LEVEL3: fountainBlue
  HTML_TAG_TREE_LEVEL4: malibu
  HTML_TAG_TREE_LEVEL5: purple
  INDENT_GUIDE: 3b4048
  LINE_NUMBER_ON_CARET_ROW_COLOR: '737984'
  LINE_NUMBERS_COLOR: '495162'
  METHOD_SEPARATORS_COLOR: 3b4048
  MODIFIED_LINES_COLOR: whiskey
  QUESTION_HINT: 376c89
  RIGHT_MARGIN_COLOR: '606368'
  SELECTED_INDENT_GUIDE: '606368'
  SELECTED_TEARLINE_COLOR: 6b6e73
  SELECTION_BACKGROUND: 3e4350
  SEPARATOR_BELOW_COLOR: ''
  TEARLINE_COLOR: 4f575f
  VISUAL_INDENT_GUIDE: 3b4048
  WHITESPACES: 4b575f
inheriting-attributes:
  ANNOTATION_NAME_ATTRIBUTES: DEFAULT_METADATA
  Class: CLASS_NAME_ATTRIBUTES
  CSS.IMPORTANT: DEFAULT_KEYWORD
  CSS.KEYWORD: DEFAULT_KEYWORD
  CSS.TAG_NAME: HTML_TAG_NAME
  CUSTOM_KEYWORD1_ATTRIBUTES: DEFAULT_KEYWORD
  CUSTOM_STRING_ATTRIBUTES: DEFAULT_STRING
  CUSTOM_VALID_STRING_ESCAPE_ATTRIBUTES: DEFAULT_VALID_STRING_ESCAPE
  DEFAULT_IDENTIFIER: TEXT
  DEFAULT_REASSIGNED_LOCAL_VARIABLE: DEFAULT_LOCAL_VARIABLE
  DEFAULT_REASSIGNED_PARAMETER: DEFAULT_PARAMETER
  DEFAULT_STATIC_METHOD: DEFAULT_FUNCTION_DECLARATION
  DEFAULT_TEMPLATE_LANGUAGE_COLOR: TEXT
  Groovy method declaration: METHOD_DECLARATION_ATTRIBUTES
  HTML_ATTRIBUTE_NAME: DEFAULT_ATTRIBUTE
  HTML_ATTRIBUTE_VALUE: DEFAULT_STRING
  HTML_ENTITY_REFERENCE: DEFAULT_ENTITY
  HTML_TAG: DEFAULT_TAG
  JAVA_KEYWORD: DEFAULT_KEYWORD
  JAVA_VALID_STRING_ESCAPE: DEFAULT_VALID_STRING_ESCAPE
  KOTLIN_ANNOTATION: ANNOTATION_NAME_ATTRIBUTES
  KOTLIN_LABEL: DEFAULT_LABEL
  KOTLIN_PACKAGE_FUNCTION_CALL: DEFAULT_STATIC_METHOD
  KOTLIN_TYPE_PARAMETER: TYPE_PARAMETER_NAME_ATTRIBUTES
  Static method access: STATIC_METHOD_ATTRIBUTES
  Static property reference ID: STATIC_FINAL_FIELD_ATTRIBUTES
  STATIC_METHOD_ATTRIBUTES: DEFAULT_STATIC_METHOD
  XML_ATTRIBUTE_NAME: DEFAULT_ATTRIBUTE
attributes:
  ANGLE_BRACKETS_RAINBOW_COLOR0: ffd700
  ANGLE_BRACKETS_RAINBOW_COLOR1: da70d6
  ANGLE_BRACKETS_RAINBOW_COLOR2: 87cefa
  ANGLE_BRACKETS_RAINBOW_COLOR3: ffd700
  ANGLE_BRACKETS_RAINBOW_COLOR4: da70d6
  ANNOTATION_ATTRIBUTE_NAME_ATTRIBUTES: whiskey
  APACHE_CONFIG.ARG_LEXEM: green
  APACHE_CONFIG.COMMENT:
    foreground: 59626f
    italic: theme
  APACHE_CONFIG.IDENTIFIER: c679dd
  BAD_CHARACTER:
    background: 9b3636
  BOOKMARKS_ATTRIBUTES: {}
  BREADCRUMBS_CURRENT:
    foreground: lightWhite
    background: 353a46
  BREADCRUMBS_DEFAULT: lightWhite
  BREADCRUMBS_HOVERED:
    foreground: lightWhite
    background: 444b5a
  BREADCRUMBS_INACTIVE: lightWhite
  BREAKPOINT_ATTRIBUTES:
    background: 743d3d
  BUILDOUT.KEY: c679dd
  BUILDOUT.KEY_VALUE_SEPARATOR: a6b2c0
  BUILDOUT.LINE_COMMENT:
    foreground: 59626f
    italic: theme
  BUILDOUT.SECTION_NAME: d2945d
  BUILDOUT.VALUE: green
  CLASS_REFERENCE: e5c17c
  Clojure Atom: c679dd
  Clojure Character: green
  Clojure Keyword: df6a73
  Clojure Line comment:
    foreground: 59626f
    italic: theme
  Clojure Literal:
    foreground: fda5ff
    bold: always
  Clojure Numbers: d2945d
  Clojure Strings: green
  COFFEESCRIPT.BAD_CHARACTER:
    background: 6e3b3b
  COFFEESCRIPT.BLOCK_COMMENT:
    foreground: 59626f
    italic: theme
  COFFEESCRIPT.BOOLEAN: d2945d
  COFFEESCRIPT.CLASS_NAME: e5c17c
  COFFEESCRIPT.COLON: invalid
  COFFEESCRIPT.ESCAPE_SEQUENCE: 57b6c2
  COFFEESCRIPT.EXISTENTIAL: a6b2c0
  COFFEESCRIPT.EXPRESSIONS_SUBSTITUTION_MARK: be4f44
  COFFEESCRIPT.FUNCTION: c679dd
  COFFEESCRIPT.FUNCTION_BINDING: c679dd
  COFFEESCRIPT.FUNCTION_NAME: malibu
  COFFEESCRIPT.GLOBAL_VARIABLE: coral
  COFFEESCRIPT.HEREDOC_CONTENT: green
  COFFEESCRIPT.HEREDOC_ID: green
  COFFEESCRIPT.HEREGEX_CONTENT: whiskey
  COFFEESCRIPT.HEREGEX_ID: 57b6c2
  COFFEESCRIPT.JAVASCRIPT_CONTENT: purple
  COFFEESCRIPT.JAVASCRIPT_ID: green
  COFFEESCRIPT.KEYWORD: c679dd
  COFFEESCRIPT.LINE_COMMENT:
    foreground: 59626f
    italic: theme
  COFFEESCRIPT.NUMBER: d2945d
  COFFEESCRIPT.OBJECT_KEY: df6a73
  COFFEESCRIPT.OPERATIONS: a6b2c0
  COFFEESCRIPT.PROTOTYPE: malibu
  COFFEESCRIPT.REGULAR_EXPRESSION_CONTENT: 57b6c2
  COFFEESCRIPT.REGULAR_EXPRESSION_FLAG: 57b6c2
  COFFEESCRIPT.REGULAR_EXPRESSION_ID: 57b6c2
  COFFEESCRIPT.STRING: green
  COFFEESCRIPT.STRING_LITERAL: green
  COFFEESCRIPT.THIS: df6a73
  CONDITIONALLY_NOT_COMPILED:
    foreground: 59626f
    italic: theme
  CONSOLE_BLUE_BRIGHT_OUTPUT:
    foreground: malibu
    bold: always
  CONSOLE_BLUE_OUTPUT: malibu
  CONSOLE_CYAN_BRIGHT_OUTPUT:
    foreground: fountainBlue
    bold: always
  CONSOLE_CYAN_OUTPUT: fountainBlue
  CONSOLE_ERROR_OUTPUT: be5046
  CONSOLE_GRAY_OUTPUT: '828997'
  CONSOLE_GREEN_BRIGHT_OUTPUT:
    foreground: green
    bold: always
  CONSOLE_GREEN_OUTPUT: green
  CONSOLE_MAGENTA_BRIGHT_OUTPUT:
    foreground: purple
    bold: always
  CONSOLE_MAGENTA_OUTPUT: purple
  CONSOLE_NORMAL_OUTPUT: lightWhite
  CONSOLE_RANGE_TO_EXECUTE:
    effect_color: 5c6370
  CONSOLE_RED_BRIGHT_OUTPUT:
    foreground: coral
    bold: always
  CONSOLE_RED_OUTPUT: coral
  CONSOLE_SYSTEM_OUTPUT: e4e4ff
  CONSOLE_USER_INPUT:
    foreground: 6ae96a
    italic: theme
  CONSOLE_WHITE_OUTPUT: lightWhite
  CONSOLE_YELLOW_BRIGHT_OUTPUT:
    foreground: whiskey
    bold: always
  CONSOLE_YELLOW_OUTPUT: whiskey
  CONSTRUCTOR_CALL_ATTRIBUTES: chalky
  CSS.COLOR: 56b6c2
  CSS.FUNCTION: 61afef
  CSS.HASH: 61afef
  CSS.IDENT: d39a63
  CSS.PROPERTY_NAME: lightWhite
  CSS.PROPERTY_VALUE: d19a66
  CSS.PSEUDO: 61afef
  CSS.URL:
    foreground: d19a66
    effect_color: d19a66
    italic: theme
    underscored: always
  CTRL_CLICKABLE:
    foreground: malibu
    effect_color: malibu
    underscored: always
  CUSTOM_KEYWORD2_ATTRIBUTES: fda5ff
  CUSTOM_KEYWORD3_ATTRIBUTES: 71d7d7
  CUSTOM_KEYWORD4_ATTRIBUTES: ffc2c2
  DEFAULT_ATTRIBUTE: whiskey
  DEFAULT_BLOCK_COMMENT:
    foreground: dark
    italic: theme
  DEFAULT_CLASS_NAME: chalky
  DEFAULT_COMMA: {}
  DEFAULT_CONSTANT: fountainBlue
  DEFAULT_DOC_COMMENT:
    foreground: dark
    italic: theme
  DEFAULT_DOC_COMMENT_TAG: purple
  DEFAULT_DOC_COMMENT_TAG_VALUE: whiskey
  DEFAULT_ENTITY: coral
  DEFAULT_FUNCTION_CALL: malibu
  DEFAULT_FUNCTION_DECLARATION: malibu
  DEFAULT_INSTANCE_FIELD: coral
  DEFAULT_INTERFACE_NAME: e5c07b
  DEFAULT_INVALID_STRING_ESCAPE:
    foreground: fountainBlue
    effect_color: error
    underwaved: always
  DEFAULT_KEYWORD:
    foreground: purple
    italic: theme
  DEFAULT_LINE_COMMENT:
    foreground: dark
    italic: theme
  DEFAULT_METADATA:
    foreground: chalky
    italic: theme
  DEFAULT_NUMBER: whiskey
  DEFAULT_PARAMETER: whiskey
  DEFAULT_SEMICOLON: {}
  DEFAULT_STATIC_FIELD: coral
  DEFAULT_STRING: green
  DEFAULT_VALID_STRING_ESCAPE: fountainBlue
  DELETED_TEXT_ATTRIBUTES:
    background: '692424'
  DEPRECATED_ATTRIBUTES:
    effect_color: lightWhite
    strikeout: always
  DIFF_CONFLICT:
    background: 763f34
    error_stripe_color: ff6647
  DIFF_DELETED:
    background: 5b5b5b
    error_stripe_color: '747474'
  DIFF_INSERTED:
    background: 2f632f
    error_stripe_color: 99ff99
  DIFF_MODIFIED:
    background: '465983'
    error_stripe_color: 99ccff
  DJANGO_COMMENT:
    foreground: 59626f
    italic: theme
  DJANGO_FILTER: 57b6c2
  DJANGO_ID: d2945d
  DJANGO_KEYWORD: c679dd
  DJANGO_NUMBER: d2945d
  DJANGO_STRING_LITERAL: green
  DJANGO_TAG_NAME: c676df
  DUPLICATE_FROM_SERVER: {}
  EDITORCONFIG_VARIABLE: coral
  ENUM_CONST: green
  ERRORS_ATTRIBUTES:
    effect_color: error
    error_stripe_color: error
    underwaved: always
  EXECUTIONPOINT_ATTRIBUTES:
    foreground: '101'
    background: c7c7ff
  FIRST SYMBOL IN LIST:
    foreground: df6a73
    bold: always
  FOLDED_TEXT_ATTRIBUTES:
    foreground: 878e9b
    background: '313741'
    underwaved: always
  FOLLOWED_HYPERLINK_ATTRIBUTES:
    foreground: purple
    effect_color: purple
    underscored: always
  GENERIC_SERVER_ERROR_OR_WARNING:
    effect_color: ff8c00
    error_stripe_color: ff8c00
    underwaved: always
  GHERKIN_OUTLINE_PARAMETER_SUBSTITUTION: e06c75
  GHERKIN_REGEXP_PARAMETER: green
  GHERKIN_TABLE_PIPE: {}
  GO_BRACES: aeb6c0
  GO_BRACKET: aeb6c0
  GO_BUILTIN_CONSTANT:
    foreground: d2945d
    italic: theme
  GO_BUILTIN_FUNCTION: 57b6c2
  GO_BUILTIN_FUNCTION_CALL: 57b6c2
  GO_BUILTIN_TYPE: c679dd
  GO_BUILTIN_TYPE_REFERENCE: c679dd
  GO_BUILTIN_VARIABLE: d2945d
  GO_COMMA: aeb6c0
  GO_EXPORTED_FUNCTION:
    foreground: malibu
    italic: theme
  GO_EXPORTED_FUNCTION_CALL: 57b6c2
  GO_KEYWORD: c679dd
  GO_LOCAL_CONSTANT:
    foreground: coral
    italic: theme
  GO_LOCAL_FUNCTION: malibu
  GO_LOCAL_FUNCTION_CALL: 57b6c2
  GO_LOCAL_VARIABLE_CALL: 57b6c2
  GO_METHOD_RECEIVER: aeb6c0
  GO_NUMBER: d2945d
  GO_OPERATOR: c679dd
  GO_PACKAGE_EXPORTED_CONSTANT:
    foreground: coral
    italic: theme
  GO_PACKAGE_EXPORTED_VARIABLE_CALL: 57b6c2
  GO_PACKAGE_LOCAL_CONSTANT:
    foreground: coral
    italic: theme
  GO_PACKAGE_LOCAL_VARIABLE_CALL: 57b6c2
  GO_SCOPE_VARIABLE: aeb6c0
  GO_SEMICOLON: aeb6c0
  GO_STRING: green
  GO_STRUCT_EXPORTED_MEMBER_CALL: 57b6c2
  GO_STRUCT_LOCAL_MEMBER_CALL: 57b6c2
  GO_TYPE_REFERENCE: aeb6c0
  GQL_ID: d2945d
  GQL_INT_LITERAL: d2945d
  GQL_KEYWORD: c679dd
  GQL_STRING_LITERAL: green
  HAML_CLASS: df6a73
  HAML_COMMENT:
    foreground: 59626f
    italic: theme
  HAML_ID: df6a73
  HAML_STRING: green
  HAML_STRING_INTERPOLATED: green
  HTML_TAG_NAME: coral
  HYPERLINK_ATTRIBUTES:
    foreground: purple
    effect_color: purple
    underscored: always
  IDENTIFIER_UNDER_CARET_ATTRIBUTES:
    background: 484e5b
  IMPLICIT_ANONYMOUS_CLASS_PARAMETER_ATTRIBUTES: {}
  INACTIVE_HYPERLINK_ATTRIBUTES:
    effect_color: lightWhite
    underscored: always
  INFO_ATTRIBUTES:
    effect_color: chalky
    error_stripe_color: chalky
    underwaved: always
  INJECTED_LANGUAGE_FRAGMENT: {}
  INLINE_PARAMETER_HINT:
    foreground: lightWhite
    background: '414855'
  INLINE_PARAMETER_HINT_CURRENT:
    foreground: lightWhite
    background: 48709b
  INLINE_PARAMETER_HINT_HIGHLIGHTED:
    foreground: lightWhite
    background: dark
  IVAR: df6a73
  JAVA_STRING: green
  JS.ATTRIBUTE:
    background: '423535'
  JS.MODULE_NAME: e5c07b
  JS.REGEXP: 56b6c2
  JSON.KEYWORD: d19a66
  JSON.PROPERTY_KEY: e06c75
  JS.STATIC_MEMBER_VARIABLE:
    foreground: fda5ff
    bold: always
  KOTLIN_BACKING_FIELD_VARIABLE: {}
  KOTLIN_CLOSURE_DEFAULT_PARAMETER: {}
  KOTLIN_DYNAMIC_FUNCTION_CALL:
    foreground: 61afef
    italic: always
  KOTLIN_DYNAMIC_PROPERTY_CALL:
    foreground: e06c75
    italic: always
  KOTLIN_MUTABLE_VARIABLE:
    italic: always
  KOTLIN_NAMED_ARGUMENT: d19a66
  KOTLIN_SMART_CAST_RECEIVER: {}
  KOTLIN_SMART_CAST_VALUE: {}
  KOTLIN_SMART_CONSTANT: {}
  KOTLIN_VARIABLE_AS_FUNCTION: 61afef
  KOTLIN_VARIABLE_AS_FUNCTION_LIKE: 61afef
  LABEL: c679dd
  LESS_ID_SELECTOR: malibu
  LESS_OPERATORS: lightWhite
  LESS_TAG_NAME: purple
  LESS_VARIABLE: df6a73
  List/map to object conversion: malibu
  LIVE_TEMPLATE_ATTRIBUTES:
    effect_color: error
  LOCALE.LINE_COMMENT:
    foreground: 59626f
    italic: theme
  LOCALE.MSGCTXT_KEYWORD: c679dd
  LOCALE.MSGID_KEYWORD: c679dd
  LOCALE.MSGID_PLURAL_KEYWORD: c679dd
  LOCALE.MSGSTR_KEYWORD: c679dd
  LOCALE.MSGSTR_PLURAL_KEYWORD: c679dd
  LOCALE.STRING_LITERAL: green
  LOG_WARNING_OUTPUT: chalky
  MACRONAME: malibu
  MARKED_FOR_REMOVAL_ATTRIBUTES:
    effect_color: error
    strikeout: always
  MATCHED_BRACE_ATTRIBUTES:
    background: 515a6b
  MESSAGE_ARGUMENT: malibu
  NOT_USED_ELEMENT_ATTRIBUTES: 7f8591
  OC_FORMAT_TOKEN: green
  OC.BLOCK_COMMENT:
    foreground: 59626f
    italic: theme
  OC.CPP_KEYWORD: c679dd
  OC.DIRECTIVE: c679dd
  OC.EXTERN_VARIABLE: df6a73
  OC.FUNCTION: malibu
  OC.GLOBAL_VARIABLE: df6a73
  OC.KEYWORD: c679dd
  OC.LINE_COMMENT:
    foreground: 59626f
    italic: theme
  OC.LOCAL_VARIABLE: df6a73
  OC.NUMBER: d2945d
  OC.PARAMETER: a6b2c0
  OC.PROPERTY: df6a73
  OC.SELFSUPERTHIS: df6a73
  OC.STRING: green
  OC.STRUCT_FIELD: green
  PHP_BAD_CHARACTER:
    background: 6e3b3b
  PHP_COMMENT:
    foreground: 59626f
    italic: theme
  PHP_CONSTANT: d2945d
  PHP_DOC_COMMENT_ID:
    foreground: 59626f
    italic: theme
  PHP_DOC_TAG:
    bold: always
  PHP_ESCAPE_SEQUENCE: 57b6c2
  PHP_EXEC_COMMAND_ID: green
  PHP_HEREDOC_CONTENT: green
  PHP_HEREDOC_ID:
    bold: always
  PHP_KEYWORD: c679dd
  PHP_MARKUP_ID:
    background: 223f22
  PHP_NUMBER: d2945d
  PHP_OPERATION_SIGN: a6b2c0
  PHP_SCRIPTING_BACKGROUND:
    background: 2a2d32
  PHP_STRING: green
  PHP_TAG: c679dd
  PHP_VAR: c679dd
  PROTOCOL_REFERENCE: e5c17c
  PUPPET_BAD_CHARACTER:
    background: 6e3b3b
  PUPPET_BLOCK_COMMENT:
    foreground: 59626f
    italic: theme
  PUPPET_CLASS: e5c17c
  PUPPET_ESCAPE_SEQUENCE: 57b6c2
  PUPPET_KEYWORD: c679dd
  PUPPET_NUMBER: d2945d
  PUPPET_OPERATION_SIGN: a6b2c0
  PUPPET_REGEX: 57b6c2
  PUPPET_SQ_STRING: green
  PUPPET_STRING: green
  PUPPET_VARIABLE_INTERPOLATION: green
  PY.BUILTIN_NAME: 57b6c2
  PY.CLASS_DEFINITION: e5c17c
  PY.DECORATOR: malibu
  PY.DOC_COMMENT: 98c476
  PY.FUNC_DEFINITION: malibu
  PY.INVALID_STRING_ESCAPE:
    foreground: 68e868
    background: '481515'
  PY.KEYWORD: c679dd
  PY.LINE_COMMENT:
    foreground: 59626f
    italic: theme
  PY.NUMBER: d2945d
  PY.PARAMETER: whiskey
  PY.PREDEFINED_USAGE: coral
  PY.SELF_PARAMETER: coral
  PY.STRING: green
  PY.VALID_STRING_ESCAPE: 57b6c2
  REGEXP.BAD_CHARACTER:
    background: 6e3b3b
  REGEXP.CHAR_CLASS: 57b6c2
  REGEXP.COMMENT:
    foreground: 59626f
    italic: theme
  REGEXP.ESC_CHARACTER: 57b6c2
  REGEXP.INVALID_STRING_ESCAPE:
    foreground: 68e868
    background: '481515'
  REGEXP.META: c679dd
  REGEXP.QUOTE_CHARACTER: 57b6c2
  REGEXP.REDUNDANT_ESCAPE: 57b6c2
  REST.EXPLICIT: c679dd
  REST.FIELD: c679dd
  REST.FIXED:
    background: 48485f
  REST.INLINE:
    background: '273627'
  REST.INTERPRETED:
    background: 4d5d3d
  REST.LINE_COMMENT:
    foreground: 59626f
    italic: theme
  REST.REF.NAME: green
  REST.SECTION.HEADER: d2945d
  RHTML_COMMENT_ID:
    foreground: 59626f
    italic: theme
  RHTML_EXPRESSION_END_ID: be4f44
  RHTML_EXPRESSION_START_ID: be4f44
  RHTML_OMIT_NEW_LINE_ID: be4f44
  RHTML_SCRIPTLET_END_ID: be4f44
  RHTML_SCRIPTLET_START_ID: be4f44
  ROUND_BRACKETS_RAINBOW_COLOR0: ffd700
  ROUND_BRACKETS_RAINBOW_COLOR1: da70d6
  ROUND_BRACKETS_RAINBOW_COLOR2: 87cefa
  ROUND_BRACKETS_RAINBOW_COLOR3: ffd700
  ROUND_BRACKETS_RAINBOW_COLOR4: da70d6
  RUBY_COMMENT:
    foreground: dark
    italic: theme
  RUBY_CONSTANT: d2945d
  RUBY_CONSTANT_DECLARATION: whiskey
  RUBY_CVAR: df6a73
  RUBY_ESCAPE_SEQUENCE: 57b6c2
  RUBY_EXPR_IN_STRING: be5046
  RUBY_GVAR: df6a73
  RUBY_HASH_ASSOC: a6b2c0
  RUBY_HEREDOC_CONTENT: green
  RUBY_HEREDOC_ID: green
  RUBY_INTERPOLATED_STRING: green
  RUBY_INVALID_ESCAPE_SEQUENCE:
    foreground: 68e868
    background: '481515'
  RUBY_IVAR: df6a73
  RUBY_KEYWORD: purple
  RUBY_LINE_CONTINUATION: a6b2c0
  RUBY_LOCAL_VAR_ID: lightWhite
  RUBY_METHOD_NAME: malibu
  RUBY_NTH_REF: coral
  RUBY_NUMBER: d2945d
  RUBY_OPERATION_SIGN: a6b2c0
  RUBY_PARAMDEF_CALL: lightWhite
  RUBY_PARAMETER_ID: lightWhite
  RUBY_REGEXP: 57b6c2
  RUBY_SPECIFIC_CALL: malibu
  RUBY_STRING: green
  RUBY_SYMBOL: fountainBlue
  RUBY_WORDS: green
  RUNTIME_ERROR:
    effect_color: ff8c00
    error_stripe_color: error
    dotted-line: always
  SASS_COMMENT:
    foreground: 59626f
    italic: theme
  SASS_DEFAULT: c679dd
  SASS_EXTEND: c679dd
  SASS_FUNCTION: 57b6c2
  SASS_IDENTIFIER: d2945d
  SASS_IMPORTANT: c679dd
  SASS_KEYWORD: c679dd
  SASS_MIXIN: d2945d
  SASS_NUMBER: d2945d
  SASS_PROPERTY_NAME: d2945d
  SASS_PROPERTY_VALUE: 68e868
  SASS_STRING: green
  SASS_TAG_NAME: c679dd
  SASS_URL: df6a73
  SASS_VARIABLE: df6a73
  SEARCH_RESULT_ATTRIBUTES:
    background: 42557b
    effect_color: 457dff
  SLIM_BAD_CHARACTER:
    foreground: 272b33
    background: f2777a
  SLIM_CLASS: df6a73
  SLIM_COMMENT:
    foreground: 59626f
    italic: theme
  SLIM_DOCTYPE_KWD: df6a73
  SLIM_FILTER: df6a73
  SLIM_ID: df6a73
  SLIM_INTERPOLATION: green
  SLIM_STRING_INTERPOLATED: green
  SLIM_TAG: df6a73
  SLIM_TAG_ATTR_KEY: d2945d
  SMARTY_BACKGROUND:
    background: 2a2d32
  SMARTY_BAD_CHARACTER:
    background: 6e3b3b
  SMARTY_COMMENT:
    foreground: 59626f
    italic: theme
  SMARTY_KEYWORD: c679dd
  SMARTY_NUMBER: d2945d
  SMARTY_OPERATION_SIGN: a6b2c0
  SMARTY_STRING: green
  SQL_BAD_CHARACTER:
    background: 6e3b3b
  SQL_COLUMN: lightWhite
  SQL_COMMENT:
    foreground: 59626f
    italic: theme
  SQL_KEYWORD: c679dd
  SQL_NUMBER: d2945d
  SQL_PROCEDURE:
    foreground: malibu
    italic: theme
  SQL_SCHEMA: malibu
  SQL_STRING: green
  SQL_SYNTETIC_ENTITY: fda5ff
  SQL_TABLE: whiskey
  SQUARE_BRACKETS_RAINBOW_COLOR0: ffd700
  SQUARE_BRACKETS_RAINBOW_COLOR1: da70d6
  SQUARE_BRACKETS_RAINBOW_COLOR2: 87cefa
  SQUIGGLY_BRACKETS_RAINBOW_COLOR0: ffd700
  SQUIGGLY_BRACKETS_RAINBOW_COLOR1: da70d6
  SQUIGGLY_BRACKETS_RAINBOW_COLOR2: 87cefa
  STATIC_METHOD_IMPORTED_ATTRIBUTES: malibu
  TAG_ATTR_KEY: d2945d
  TEMPLATE_VARIABLE_ATTRIBUTES: whiskey
  TEXT:
    foreground: lightWhite
    background: 282c34
  TEXT_SEARCH_RESULT_ATTRIBUTES:
    background: 42557b
    effect_color: 457dff
    error_stripe_color: 457dff
  TODO_DEFAULT_ATTRIBUTES:
    foreground: ff8c00
    italic: theme
  TS.MODULE_NAME: chalky
  TS.TYPE_PARAMETER: e5c07b
  TWIG_BACKGROUND:
    background: 2a2d32
  TWIG_BAD_CHARACTER:
    background: 6e3b3b
  TWIG_COMMENT:
    foreground: 59626f
    italic: theme
  TWIG_KEYWORD: c679dd
  TWIG_NUMBER: d2945d
  TWIG_OPERATION_SIGN: a6b2c0
  TWIG_STRING: green
  TYPEDEF: c679dd
  TYPE_PARAMETER_NAME_ATTRIBUTES: chalky
  TYPO:
    effect_color: green
    underwaved: always
  UNMATCHED_BRACE_ATTRIBUTES:
    background: '583535'
  Unresolved reference access: error
  WARNING_ATTRIBUTES:
    effect_color: ff8c00
    error_stripe_color: ff8c00
    underwaved: always
  WRITE_IDENTIFIER_UNDER_CARET_ATTRIBUTES:
    background: 484e5b
  WRITE_SEARCH_RESULT_ATTRIBUTES:
    background: 42557b
    effect_color: 457dff
  WRONG_REFERENCES_ATTRIBUTES: error
  XML_ATTRIBUTE_VALUE: green
  XML_COMMENT:
    foreground: 59626f
    italic: theme
  XML_ENTITY_REFERENCE: d2945d
  XML_NS_PREFIX: d2945d
  XML_PROLOGUE:
    italic: theme
  XML_TAG_NAME:
    foreground: coral
    bold: always
  YAML_ANCHOR: chalky
  YAML_SCALAR_KEY: coral
  YAML_SCALAR_LIST: green
  YAML_SCALAR_VALUE: green
  YAML_TEXT:
    foreground: green
