language: java
install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
  - sudo pip3 install -r requirements.txt
script:
  - python3 scripts/build.py
  - python3 scripts/changelog.py
  - ./gradlew build
deploy:
  - provider: releases
    api_key: $GITHUB_AUTH_TOKEN
    file_glob: true
    file: build/libs/*.jar
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: ./gradlew publishPlugin
    skip_cleanup: true
    on:
      tags: true
env:
  - GIT_TAG=$TRAVIS_TAG
notifications:
  email:
    recipients:
      - $ADMIN_EMAIL
    on_success: change
    on_failure: always
