name: Release
on:
  release:
    types:
      - created
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 25

      - run: ./gradlew buildPlugin
        env:
          VERSION: ${{ github.ref }}

      - name: Copy zip file
        run: cp build/distributions/*.zip one-dark-theme.zip

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: one-dark-theme.zip
          asset_name: one-dark-theme.zip
          asset_content_type: application/zip

      - run: ./gradlew publishPlugin
        env:
          VERSION: ${{ github.ref }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
